"""Feedback-action v1: migration onto transition_evidence_v2 (format only; no masks, no treatment change).

The golden file was generated by `digest()` below at the pre-migration commit 638b85e (the merge commit touched no
Track 1 file). It holds, per rehearsal scenario and arm, the SHA-256 of every model-facing request (canonical JSON of
the whole request: system and user messages, response schema, caps), and the independent evaluator's per-decision
results and metrics. To re-check it: check out 638b85e, copy this function there, and run it.
"""
import ast
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import unittest

from research.feedback_action_v1 import evaluate as EV, evidence as E, fixtures as F, rehearsal as R
from research.transition_evidence_v1 import transition as T1
from research.transition_evidence_v2 import transition as T2

ROOT = Path(__file__).resolve().parents[1]
TRACK = ROOT / 'research' / 'feedback_action_v1'
GOLDEN = TRACK / 'migration_v2_golden.json'


def canon(value):
    return json.dumps(value, sort_keys=True, separators=(',', ':'))


class Capture:
    def __init__(self, model):
        self.model, self.requests = model, []

    def __call__(self, request):
        self.requests.append(canon(request))
        return self.model(request)


def digest():
    out = {}
    for name, (env_name, kwargs, plan, arms, budget, tokens) in R.SCENARIOS.items():
        for arm in arms:
            capture = Capture(R.Scripted(arm, plan, tokens))
            trajectory = R.run(env_name, arm, capture, budget, kwargs)
            evaluation = EV.evaluate_trajectory(trajectory)
            out[f'{name}/{arm}'] = {'requests': [hashlib.sha256(r.encode()).hexdigest() for r in capture.requests],
                                    'decisions': evaluation['decisions'], 'metrics': evaluation['metrics']}
    return out


ADDED_ROW_KEYS = ('record_id', 'cited_record_ids',  # added by the v2 migration
                  'opportunities')  # added later by the denominator pass (protocol v2 §8); new output, not a change
ADDED_METRIC_KEYS = ('rates',)  # added by the denominator pass


def without_added(row):
    return {k: v for k, v in row.items() if k not in ADDED_ROW_KEYS}


def metrics_without_added(metrics):
    return {k: v for k, v in metrics.items() if k not in ADDED_METRIC_KEYS}


class Migration(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.golden = json.loads(GOLDEN.read_text())
        cls.now = digest()
        cls.results = R.rehearse()

    def test_golden_provenance_and_coverage(self):
        self.assertEqual(self.golden['generated_at_commit'], '638b85e')
        self.assertEqual(set(self.golden['scenarios']), set(self.now))
        self.assertEqual(sum(len(v['requests']) for v in self.golden['scenarios'].values()), 64)

    def test_a_every_model_facing_request_is_byte_identical(self):
        for key, old in self.golden['scenarios'].items():
            self.assertEqual(self.now[key]['requests'], old['requests'], key)

    def test_b_evaluator_results_and_rehearsal_outcomes_unchanged(self):
        """Unchanged except the added record ids, which must equal version 2's record_id."""
        for key, old in self.golden['scenarios'].items():
            self.assertEqual(metrics_without_added(self.now[key]['metrics']), old['metrics'], key)
            self.assertEqual([without_added(r) for r in self.now[key]['decisions']], old['decisions'], key)
        for (name, arm), (trajectory, evaluation) in self.results.items():
            for step, row in zip(trajectory['steps'], evaluation['decisions']):
                self.assertEqual(row.get('record_id'), step['record_id'])
                if step['dispatched_index'] is not None:
                    raw = trajectory['raws'][step['dispatched_index']]
                    self.assertEqual(row['record_id'], T2.record_id(raw['identity']))
                by_index = {r['identity']['action_index']: T2.record_id(r['identity'])
                            for r in trajectory['raws'][:step['raws_before']]}
                for name_, refs in row.get('cited_record_ids', {}).items():
                    block = step['adapter_decision']['procedure']
                    for cite, rid in zip(block[name_], refs):
                        index = int(cite['ref'][1:]) if cite['ref'][1:].isdigit() else None
                        self.assertEqual(rid, by_index.get(index))

    def test_b_statement_records_only_for_dispatched_actions(self):
        """The one rehearsal-output difference: a valid block whose action was not dispatched is about no transition,
        so it no longer gets a model-statement record (version 2 statements cite a record_id). It stays in its step."""
        trajectory, _ = self.results[('invalid_structured_output', 'candidate')]
        valid = [n for n, s in enumerate(trajectory['steps']) if s['adapter_decision']['procedure'] is not None]
        self.assertEqual(valid, [1, 4])
        self.assertIsNone(trajectory['steps'][1]['dispatched_index'])  # illegal action, valid block
        self.assertEqual([s['about_record_id'] for s in trajectory['model_statements']],
                         [trajectory['steps'][4]['record_id']])

    def test_c_every_record_validates_and_verifies_against_its_raws(self):
        sets = [(f"{n}/{a}", t['raws']) for (n, a), (t, _) in self.results.items()]
        sets += [(fx['id'], fx['raws']) for fx in json.loads(F.OUTPUT.read_bytes())['fixtures']]
        checked = 0
        for name, raws in sets:
            records = T2.history(raws)
            self.assertEqual(T2.verify_history(records, raws), [], name)
            for raw in raws:
                record = T2.build(raw)
                self.assertEqual(T2.verify(record, raw), [], name)
                self.assertEqual(T2.to_v1(record), T1.build(raw))
                checked += 1
        self.assertEqual(checked, 68)  # 52 rehearsal transitions + 16 fixture transitions

    def test_c_context_and_available_actions(self):
        for (name, arm), (trajectory, _) in self.results.items():
            for step in trajectory['steps']:
                if step['dispatched_index'] is None:
                    continue
                record = T2.build(trajectory['raws'][step['dispatched_index']])
                self.assertEqual(record['context']['available_actions_before'],
                                 {'status': 'measured', 'value': step['legal_actions']})
                if record['dispatch']['status'] == 'acknowledged':
                    self.assertEqual(record['environment']['reported']['available_actions_changed'],
                                     {'status': 'measured', 'value': False})
        for fx in json.loads(F.OUTPUT.read_bytes())['fixtures']:  # fixtures keep v1 raw bytes: reported as absent
            self.assertEqual(T2.build(fx['raws'][0])['context']['available_actions_before']['status'], 'absent')

    def test_c_evidence_view_identical_from_v1_and_v2_records(self):
        for (name, arm), (trajectory, _) in self.results.items():
            raws = trajectory['raws']
            self.assertEqual([E.entry(r) for r in T2.history(raws)], [E.entry(r) for r in T1.history(raws)], name)

    def test_d_track_never_touches_the_region_restricted_view_or_its_module(self):
        """Every Track 1 source, including the derived live runner: no identifier, attribute, string or import
        mentions a mask (comments are not code: the derived runner keeps AEH's comment 'never mask the first
        error'), and no JSON file does."""
        for path in sorted(TRACK.rglob('*.json')):
            self.assertNotIn('mask', path.read_text().lower(), path.name)
        for path in sorted(TRACK.rglob('*.py')):
            for node in ast.walk(ast.parse(path.read_text())):
                words = ([node.id] if isinstance(node, ast.Name) else [node.attr] if isinstance(node, ast.Attribute)
                         else [node.value] if isinstance(node, ast.Constant) and isinstance(node.value, str)
                         else [a.name for a in node.names] if isinstance(node, (ast.Import, ast.ImportFrom)) else [])
                self.assertFalse(any('mask' in w.lower() for w in words), f'{path.name}: {words}')
        for path in sorted(TRACK.rglob('*.py')):
            for node in ast.walk(ast.parse(path.read_text())):
                if isinstance(node, (ast.Import, ast.ImportFrom)):
                    names = [a.name for a in node.names] + [getattr(node, 'module', '') or '']
                    self.assertFalse(any('masks' in n for n in names), path.name)
                if isinstance(node, ast.Call) and getattr(node.func, 'attr', None) in ('build', 'history', 'verify',
                                                                                      'verify_history', 'extend'):
                    self.assertTrue(len(node.args) <= {'build': 1, 'history': 1, 'verify': 2, 'verify_history': 2,
                                                       'extend': 2}[node.func.attr] and not node.keywords,
                                    f'{path.name}: {node.func.attr} called with extra arguments')
        for (name, arm), (trajectory, _) in self.results.items():
            for step in trajectory['steps']:
                self.assertNotIn('mask', step['request_user_content'].lower())
            for record in T2.history(trajectory['raws']):
                self.assertEqual(record['masked']['status'], 'unavailable')  # nothing was ever supplied

    def test_d_the_module_is_never_imported_by_this_track(self):
        code = ('import sys\n'
                'from research.feedback_action_v1 import adapter, environments, evaluate, evidence, fixtures, rehearsal\n'
                'from research.feedback_action_v1 import derive, token_audit\n'
                'from research.feedback_action_v1.live import policy, runner, service, engine, evidence as ev, fake_server\n'
                'rehearsal.rehearse(); fixtures.generate(); fake_server.FakeServer()\n'
                'print("research.transition_evidence_v2.masks" in sys.modules)\n')
        out = subprocess.run([sys.executable, '-c', code], cwd=ROOT, capture_output=True, text=True, check=True)
        self.assertEqual(out.stdout.strip(), 'False')

    def test_e_fixtures_regenerate_byte_identically(self):
        raw = F.encode(F.generate())
        self.assertEqual(raw, F.OUTPUT.read_bytes())
        self.assertEqual(hashlib.sha256(raw).hexdigest(),
                         'a19cbb78989d11d6f9592210db1aecab11d01648ce192370f41a332c154853a9')


if __name__ == '__main__':
    Path(sys.argv[1]).write_text(json.dumps({'generated_at_commit': sys.argv[2], 'scenarios': digest()},
                                            sort_keys=True, indent=1) + '\n')
